-- AstroScan Telescope Bridge — DDL (V1, Phase 2 deployment target)
-- File: /opt/astroscan/data/telescope_bridge.db  (SEPARATE from main DB)
-- Engine: SQLite 3.31+ (WAL mode, foreign_keys=ON)
--
-- Conventions:
--   - all primary keys are UUID v4 stored as TEXT(36)
--   - all timestamps stored as ISO-8601 UTC TEXT (compatible with datetime.fromisoformat)
--   - table prefix tb_ to avoid any collision with main AstroScan tables
--   - foreign keys ON DELETE CASCADE for session-bound resources

PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
PRAGMA foreign_keys = ON;

-- ── tb_pair_codes ────────────────────────────────────────────────────
-- One-shot pairing codes generated by the dashboard. TTL 10 min,
-- single-use, consumed by /pair/confirm.
CREATE TABLE IF NOT EXISTS tb_pair_codes (
    code        TEXT PRIMARY KEY,            -- 6 digits, e.g. "479201"
    user_id     TEXT NOT NULL,               -- AstroScan user id
    label       TEXT,                        -- user-supplied, optional
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    consumed_at TEXT,                        -- NULL until /pair/confirm
    consumed_by_agent_id TEXT
);
CREATE INDEX IF NOT EXISTS ix_pair_user ON tb_pair_codes(user_id);
CREATE INDEX IF NOT EXISTS ix_pair_expires ON tb_pair_codes(expires_at);

-- ── tb_agents ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tb_agents (
    agent_id          TEXT PRIMARY KEY,
    user_id           TEXT NOT NULL,
    fingerprint       TEXT NOT NULL,         -- sha256 of hostname+install_id
    label             TEXT,
    agent_version     TEXT,
    os                TEXT,                   -- linux|windows|macos
    created_at        TEXT NOT NULL,
    last_seen_at      TEXT,
    last_jwt_jti      TEXT,                   -- for revocation tracking
    is_revoked        INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_agents_user ON tb_agents(user_id);

-- ── tb_sessions ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tb_sessions (
    session_id   TEXT PRIMARY KEY,
    agent_id     TEXT NOT NULL REFERENCES tb_agents(agent_id) ON DELETE CASCADE,
    user_id      TEXT NOT NULL,
    issued_at    TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    last_seen_at TEXT,
    revoked_at   TEXT
);
CREATE INDEX IF NOT EXISTS ix_sessions_agent ON tb_sessions(agent_id);
CREATE INDEX IF NOT EXISTS ix_sessions_user ON tb_sessions(user_id);

-- ── tb_devices ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tb_devices (
    device_id        TEXT PRIMARY KEY,
    agent_id         TEXT NOT NULL REFERENCES tb_agents(agent_id) ON DELETE CASCADE,
    user_id          TEXT NOT NULL,
    device_local_id  TEXT NOT NULL,           -- e.g. "alpaca:telescope:0"
    kind             TEXT NOT NULL,           -- mount|camera|focuser|…
    name             TEXT,
    driver           TEXT,                    -- alpaca|ascom_com|indi|mock
    capabilities_json TEXT,                   -- JSON array of strings
    consent_json     TEXT,                    -- JSON object of granted properties
    first_seen_at    TEXT NOT NULL,
    last_seen_at     TEXT,
    UNIQUE (agent_id, device_local_id)
);
CREATE INDEX IF NOT EXISTS ix_devices_user ON tb_devices(user_id);

-- ── tb_telemetry ─────────────────────────────────────────────────────
-- Append-only. Retention: 30 days (cron job pruning, NOT in V1).
CREATE TABLE IF NOT EXISTS tb_telemetry (
    sample_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    device_id    TEXT NOT NULL REFERENCES tb_devices(device_id) ON DELETE CASCADE,
    user_id      TEXT NOT NULL,
    kind         TEXT NOT NULL,
    ts           TEXT NOT NULL,                -- agent-supplied
    ingested_at  TEXT NOT NULL,                -- server-supplied
    payload_json TEXT NOT NULL                 -- the validated sample blob
);
CREATE INDEX IF NOT EXISTS ix_telemetry_device_ts ON tb_telemetry(device_id, ts DESC);
CREATE INDEX IF NOT EXISTS ix_telemetry_user_ts   ON tb_telemetry(user_id, ts DESC);

-- ── tb_audit ─────────────────────────────────────────────────────────
-- Security-relevant events. Read by the SOC dashboard later.
CREATE TABLE IF NOT EXISTS tb_audit (
    event_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    ts          TEXT NOT NULL,
    actor_kind  TEXT NOT NULL,                 -- user|agent|system
    actor_id    TEXT,                          -- user_id or agent_id
    event_type  TEXT NOT NULL,                 -- pair_init|pair_confirm|session_revoke|…
    outcome     TEXT NOT NULL,                 -- ok|denied|error
    detail      TEXT                           -- short message, no PII
);
CREATE INDEX IF NOT EXISTS ix_audit_ts ON tb_audit(ts DESC);

-- ── tb_replay_nonces ─────────────────────────────────────────────────
-- Short-TTL cache of seen nonces (5-min sliding window).
CREATE TABLE IF NOT EXISTS tb_replay_nonces (
    nonce      TEXT PRIMARY KEY,
    seen_at    TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_nonce_expires ON tb_replay_nonces(expires_at);
